### ISSUE TITLE
脚底踩着武器的bug

### ISSUE THREAD

**Issue by Luzhiyongg** [THU-SE2020-Don-t-Stay-Up/TsinghuaRider#36]
![截图](https://user-images.githubusercontent.com/71517277/100497258-21aff580-3195-11eb-925d-dc56fb37cba5.jpg)

按几次H键之后会出现这样的bug，脚底下踩着一把武器。

**Comment by Iamtheboneofmysword** [comment]
脚下踩着的武器是按下H后新建的，由于蛟蛟把人物的参考点移动到脚上，所以每次新建都以这个点为准，把武器生成到脚上了，我们得重新改生成的handleOffset。至于多了一个武器，看看这时人物是不是挂了两把武器，而且人物是不是有个icon的child GameObject？如果是的话，在设置Mahou Prefab时，把她child GameObject中的初始武器的顺序调到icon之上。我试试能不能把检测人物当前武器的逻辑写好一点，不要再默认把第0个child GameObject作为她武器

**Comment by guhaiqiao** [comment]
已经采用getComponentInChildren获取当前武器，不再需要把武器调到第一位
