### ISSUE TITLE
人物无法移动的bug

### ISSUE THREAD

**Issue by Luzhiyongg** [THU-SE2020-Don-t-Stay-Up/TsinghuaRider#37]
从Scenes中删除人物之后，从Prefab拖拽出一个新人物出来。这个人物无法响应键盘动作，也无法射出子弹。但是枪依旧可以跟随鼠标

**Comment by guhaiqiao** [comment]
untiy下面的console具体报错信息是什么

**Comment by Iamtheboneofmysword** [comment]
已经修改了UI控件的获取方式，现在只需要把人物prefab和UI的prefab放入同一个Scene就好了
