### ISSUE TITLE
敌人的生成时机

### ISSUE THREAD

**Issue by Luzhiyongg** [THU-SE2020-Don-t-Stay-Up/TsinghuaRider#85]
如果敌人打太快的话，需要等一段时间；
但如果敌人打太慢，敌人数量压力就有点大。
是否能够加入判断机制，只有在当前这波敌人打完才会生成下一波？ @Tokamak-307

**Comment by Tokamak-307** [comment]
可以

**Comment by guhaiqiao** [comment]
其实可以考虑加一个按键直接生成下一波，增加游戏的快乐[旺柴]

**Comment by Tokamak-307** [comment]
已改成打完一波生成下一波，太久不打也会生成。
