### ISSUE TITLE
近战刀光的显示

### ISSUE THREAD

**Issue by guhaiqiao** [THU-SE2020-Don-t-Stay-Up/TsinghuaRider#91]
order layer中将刀光调至了30，在ItemTestScene中可以正常显示刀光，但StartScene中发射了刀光（有伤害效果）却无法显示，好象是被地形挡住了

**Comment by guhaiqiao** [comment]
以及现在的刀光感觉有点小

**Comment by Iamtheboneofmysword** [comment]
不知为什么，游戏scene中Bullet以下的层中刀光都不会显示，只有在Bullet及以上才会。但是在itemTest scene中就不会出现这样的情况。怀疑是Unity渲染多层出问题了……
现在暂时把刀光都移到了Bullet层。当时为什么要加一个刀光层？

**Comment by guhaiqiao** [comment]
子弹碰到刀光层自动Destroy，实现刀光劈砍子弹的功能

**Comment by Iamtheboneofmysword** [comment]
通过刀光脚本中检测碰撞物体是否是子弹，实现了刀光切子弹
